version: '3.9'

services:
  nginx:
    container_name: nginx-lab
    hostname: nginx-lab.dev
    image: nginx
    restart: "always"
    volumes:
      - ./files/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./files/conf/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    networks:
      - "frontend"
    environment:
      - NGINX_HOST=nginx-lab.dev
      - NGINX_PORT=80
    
networks:
  frontend: {}

